name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Compute Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2-beta
      with:
        fetch-depth: 2
    - name: Show event
      run: |
        cat $GITHUB_EVENT_PATH
    - name: Collect coverage
      run: |
        pip install --user coverage
        coverage erase
        coverage run -m unittest discover
        coverage xml
    - name: Create EasyCov coverage
      run: |
        pip install --user .
        
