name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Compute Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
      with:
        fetch-depth: 2
    - name: Show event
      run: |
        cat $GITHUB_EVENT_PATH
