name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Compute Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Setup paths and env
      run: |
        mkdir -p $HOME/.local/bin
        mkdir -p $HOME/.local/lib/pkgconfig
        echo "::set-env name=PKG_CONFIG_PATH::$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"
        echo "::set-env name=LD_LIBRARY_PATH::$HOME/.local/lib:$LD_LIBRARY_PATH"
        echo "::set-env name=PATH::$HOME/.local/bin:$PATH"
        env
    - name: Checkout source code
      uses: actions/checkout@v2-beta
      with:
        fetch-depth: 2
    - name: Show event
      run: |
        cat $GITHUB_EVENT_PATH
        echo ${{ github.event_name }}
    - name: Collect coverage
      run: |
        pip install --user coverage
        pip install --user wheel
        pip install --user .
        hash -r
        coverage erase
        coverage run -m unittest discover
        coverage xml
    - name: Coverage
      uses: EasyCov/EasyCov@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        xml-coverage: coverage.xml
